-- Seed David Lloyd Clubs UK padel sites as members-only directory venues (24 Sep 2026)
--
-- Purpose: list all 71 David Lloyd UK clubs that have a padel page on davidlloyd.co.uk
-- (verified 24 Sep 2026) in the XPLAY club directory, so players can find them and
-- organise XPLAY matches there using the external-club "I've booked the court" flow.
--
-- Rule: external_provider = 'davidlloyd' means MEMBERS-ONLY, NEVER COLLECTED.
--   * No live availability grid, no collector, no member-account login (decision 24 Sep 2026).
--   * external_tenant_id is set to 'dl:<slug>' ON PURPOSE: the Playtomic/Padelmates collectors'
--     `map` modes only look at clubs with external_tenant_id IS NULL, and
--     dispatch_external_collect only picks provider in ('playtomic','padelmates'),
--     so these rows stay out of every collector without touching collector code.
--   * Six clubs were showing "Padel - Coming Soon" on 24 Sep 2026 (cheam, hamilton, kings-hill,
--     leicester-narborough, norwich, worcester): their description ends "Padel courts opening soon."
--
-- Data: name/address/postcode/phone/email from each club page's schema.org HealthClub JSON-LD;
-- coordinates from the club page's map pin (postcodes.io for the 7 pages without one).
--
-- Street excludes the town (city column holds it).
--
-- Rollback:
--   delete from public.clubs where external_provider = 'davidlloyd' and claimed = false;

insert into public.clubs
  (club_name, source, external_provider, external_tenant_id, website, address_line_1, city, postcode, country, latitude, longitude, phone, email, description, claimed)
values
  ('David Lloyd Aberdeen', 'directory', 'davidlloyd', 'dl:aberdeen', 'https://www.davidlloyd.co.uk/clubs/aberdeen/club-facilities/padel/', 'Garthdee Road', 'Aberdeen', 'AB10 7AY', 'UK', 57.1215596, -2.1255835, '+44 (0)1707 283500', 'aberdeen@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Acton Park', 'directory', 'davidlloyd', 'dl:acton-park', 'https://www.davidlloyd.co.uk/clubs/acton-park/padel/', 'East Acton Lane, West London', 'London', 'W3 7HB', 'UK', 51.511947, -0.253457, '+44 (0)1707 283500', 'actonpark@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Basildon', 'directory', 'davidlloyd', 'dl:basildon', 'https://www.davidlloyd.co.uk/clubs/basildon/club-facilities/padel/', 'Festival Leisure Park, Pipps Hill Road South', 'Basildon', 'SS14 3DG', 'UK', 51.5844391, 0.4630259, '+44 (0)1707 283500', 'basildon@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Beckenham', 'directory', 'davidlloyd', 'dl:beckenham', 'https://www.davidlloyd.co.uk/clubs/beckenham/club-facilities/padel/', 'Stanhope Grove, Beckenham, Kent', 'Beckenham', 'BR3 3HL', 'UK', 51.3961187, -0.035121, '+44 (0)1707 283500', 'beckenham@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Belfast', 'directory', 'davidlloyd', 'dl:belfast', 'https://www.davidlloyd.co.uk/clubs/belfast/club-facilities/padel/', '115 Old Dundonald Road', 'Belfast', 'BT16 1DL', 'UK', 54.5864555, -5.8220317, '+44 (0)1707 283500', 'belfast@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Bicester', 'directory', 'davidlloyd', 'dl:bicester', 'https://www.davidlloyd.co.uk/clubs/bicester/club-facilities/padel/', 'Wendlebury Road', 'Bicester', 'OX25 2BX', 'UK', 51.8862864, -1.1674064, '+44 (0)1707 283500', 'bicester@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Birmingham', 'directory', 'davidlloyd', 'dl:birmingham', 'https://www.davidlloyd.co.uk/clubs/birmingham/club-facilities/padel/', 'Shady Lane, Great Barr', 'Birmingham', 'B44 9ER', 'UK', 52.552454, -1.895827, '+44 (0)1707 283500', 'birmingham@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Bishops Cleeve', 'directory', 'davidlloyd', 'dl:bishops-cleeve', 'https://www.davidlloyd.co.uk/clubs/bishops-cleeve/club-facilities/padel/', 'Unit 1, Stoke Road, Bishops Cleeve, Cheltenham, Gloucestershire', 'Cheltenham', 'GL52 7BQ', 'UK', 51.9462963, -2.0823202, '+44 (0)1707 283500', null, 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Bristol Emersons Green', 'directory', 'davidlloyd', 'dl:bristol-emersons-green', 'https://www.davidlloyd.co.uk/clubs/bristol-emersons-green/club-facilities/padel/', 'Willowherb Road, Emersons Green, South Gloucestershire', 'Bristol', 'BS16 7PF', 'UK', 51.490621, -2.468402, '+44 (0)1707 283500', 'BristolEmersonsGreen@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Bristol Westbury', 'directory', 'davidlloyd', 'dl:bristol-westbury', 'https://www.davidlloyd.co.uk/clubs/bristol-westbury/club-facilities/padel/', 'Greystoke Avenue, Westbury-on-Trym', 'Bristol', 'BS10 6AZ', 'UK', 51.4985701, -2.6137369, '+44 (0)1707 283500', 'bristolwestbury@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Bury St Edmunds', 'directory', 'davidlloyd', 'dl:bury-st-edmunds', 'https://www.davidlloyd.co.uk/clubs/bury-st-edmunds/club-facilities/padel/', '1 Sandlands Drive', 'Bury St Edmunds', 'IP32 6JD', 'UK', 52.268046, 0.69585, '+44 (0)1707 283500', 'burystedmunds@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Bushey', 'directory', 'davidlloyd', 'dl:bushey', 'https://www.davidlloyd.co.uk/clubs/bushey/club-facilities/padel/', 'Hartspring Lane, Bushey', 'Watford', 'WD23 2DL', 'UK', 51.6624944, -0.3638916, '+44 (0)1707 283500', 'bushey@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Cambridge', 'directory', 'davidlloyd', 'dl:cambridge', 'https://www.davidlloyd.co.uk/clubs/cambridge/club-facilities/padel/', 'Coldham''s Business Park, Coldham''s Lane', 'Cambridge', 'CB1 3LH', 'UK', 52.1939336, 0.1668678, '+44 (0)1707 283500', 'cambridge@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Cardiff', 'directory', 'davidlloyd', 'dl:cardiff', 'https://www.davidlloyd.co.uk/clubs/cardiff/club-facilities/padel/', 'Ipswich Road, Roath', 'Cardiff', 'CF23 9AQ', 'UK', 51.49977, -3.14601, '+44 (0)1707 283500', 'cardiff@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Cheadle', 'directory', 'davidlloyd', 'dl:cheadle', 'https://www.davidlloyd.co.uk/clubs/cheadle/club-facilities/padel/', 'Royal Crescent, Cheadle Royal, Cheadle, Cheshire', 'Cheadle', 'SK8 3FL', 'UK', 53.3783262, -2.2198104, '+44 (0)1707 283500', 'cheadle@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Cheam', 'directory', 'davidlloyd', 'dl:cheam', 'https://www.davidlloyd.co.uk/clubs/cheam/club-facilities/padel/', 'Ewell Road, Cheam', 'Sutton', 'SM3 8DP', 'UK', 51.3575183, -0.2197891, '+44 (0)1707 283500', 'cheam@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead. Padel courts opening soon.', false),
  ('David Lloyd Chelsea', 'directory', 'davidlloyd', 'dl:chelsea', 'https://www.davidlloyd.co.uk/clubs/chelsea/club-facilities/padel/', 'Watermeadow Lane', 'London', 'SW6 2RW', 'UK', 51.4698947, -0.1839132, '0208 543 8021', 'member.chelsea@harbourclub.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Cheshire Oaks', 'directory', 'davidlloyd', 'dl:cheshire-oaks', 'https://www.davidlloyd.co.uk/clubs/cheshire-oaks/club-facilities/padel/', 'Stanney Lane', 'Ellesmere Port', 'CH65 9JN', 'UK', 53.2639544, -2.8900679, '+44 (0)1707 283500', 'cheshireoaks@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Chigwell', 'directory', 'davidlloyd', 'dl:chigwell', 'https://www.davidlloyd.co.uk/clubs/chigwell/club-facilities/padel/', 'Roding Lane, Buckhurst Hill', 'Chigwell', 'IG9 6BJ', 'UK', 51.6272641, 0.0547958, '+44 (0)1707 283500', 'chigwell@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Chorley', 'directory', 'davidlloyd', 'dl:chorley', 'https://www.davidlloyd.co.uk/clubs/chorley/club-facilities/padel/', 'Moss Lane, Whittle-le-Woods', 'Chorley', 'PR6 8AB', 'UK', 53.6769561, -2.6218313, '+44 (0)1707 283500', 'chorley@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Colchester', 'directory', 'davidlloyd', 'dl:colchester', 'https://www.davidlloyd.co.uk/clubs/colchester/club-facilities/padel/', 'United Way, Mile End', 'Colchester', 'CO4 6AT', 'UK', 51.921789, 0.900573, '+44 (0)1707 283500', 'colchester@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Dartford', 'directory', 'davidlloyd', 'dl:dartford', 'https://www.davidlloyd.co.uk/clubs/dartford/club-facilities/padel/', 'Darenth Road, Dartford, Kent', 'Dartford', 'DA1 1NJ', 'UK', 51.4390377, 0.2250415, '+44 (0)1707 283500', 'dartford@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Derby', 'directory', 'davidlloyd', 'dl:derby', 'https://www.davidlloyd.co.uk/clubs/derby/club-facilities/padel/', 'Riverside Road, Pride Park', 'Derby', 'DE24 8HY', 'UK', 52.9166257, -1.4544847, '+44 (0)1707 283500', 'derby@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Eastbourne', 'directory', 'davidlloyd', 'dl:eastbourne', 'https://www.davidlloyd.co.uk/clubs/eastbourne/club-facilities/padel/', 'Broadwater Way, Hampden Park', 'Eastbourne', 'BN22 9PZ', 'UK', 50.792616, 0.2785466, '+44 (0)1707 283500', 'eastbourne@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Edinburgh Corstorphine', 'directory', 'davidlloyd', 'dl:edinburgh-corstorphine', 'https://www.davidlloyd.co.uk/clubs/edinburgh-corstorphine/club-facilities/padel/', '89B Glasgow Road', 'Edinburgh', 'EH12 8GZ', 'UK', 55.93896059999999, -3.3027736, '+44 (0)1707 283500', 'edinburgh@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Edinburgh Shawfair', 'directory', 'davidlloyd', 'dl:edinburgh-shawfair', 'https://www.davidlloyd.co.uk/clubs/edinburgh-shawfair/club-facilities/padel/', 'Old Dalkeith Road, Danderhall', 'Dalkeith', 'EH22 1FD', 'UK', 55.9057224, -3.1022704, '+44 (0)1707 283500', 'Sales.Shawfair@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Farnham', 'directory', 'davidlloyd', 'dl:farnham', 'https://www.davidlloyd.co.uk/clubs/farnham/club-facilities/padel/', 'Monkton Lane, Farnham, Surrey', 'Farnham', 'GU9 9ND', 'UK', 51.2264503, -0.7762224, '+44 (0)1707 283500', 'farnham@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Finchley', 'directory', 'davidlloyd', 'dl:finchley', 'https://www.davidlloyd.co.uk/clubs/finchley/club-facilities/padel/', 'Leisure Way, High Road, Finchley', 'London', 'N12 0QZ', 'UK', 51.6046188, -0.1749255, '+44 (0)1707 283500', 'finchley@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Gidea Park', 'directory', 'davidlloyd', 'dl:gidea-park', 'https://www.davidlloyd.co.uk/clubs/gidea-park/club-facilities/padel/', 'Squirrels Heath Lane, Gidea Park, Romford, Essex', 'Romford', 'RM11 2DY', 'UK', 51.5830686, 0.2173299, '+44 (0)1707 283500', 'gideapark@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Glasgow Renfrew', 'directory', 'davidlloyd', 'dl:glasgow-renfrew', 'https://www.davidlloyd.co.uk/clubs/glasgow-renfrew/club-facilities/padel/', 'Cockleshill Park, Arkleston Road, Renfrew, Renfrewshire', 'Renfrew', 'PA4 0RA', 'UK', 55.8619109, -4.407427, '+44 (0)1707 283500', 'Renfrew@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Glasgow Rouken Glen', 'directory', 'davidlloyd', 'dl:glasgow-rouken-glen', 'https://www.davidlloyd.co.uk/clubs/glasgow-rouken-glen/padel/', '2 Stewarton Road', 'Glasgow', 'G46 7UY', 'UK', 55.798987, -4.323597, '+44 (0)1707 283500', 'roukenglen@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Gloucester', 'directory', 'davidlloyd', 'dl:gloucester', 'https://www.davidlloyd.co.uk/clubs/gloucester/club-facilities/padel/', 'Delta Way, Gloucester Business Park, Brockworth', 'Gloucester', 'GL3 4BJ', 'UK', 51.8475374, -2.1707232, '+44 (0)1707 283500', 'Gloucester@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Hamilton', 'directory', 'davidlloyd', 'dl:hamilton', 'https://www.davidlloyd.co.uk/clubs/hamilton/club-facilities/padel/', 'Mote Hill', 'Hamilton', 'ML3 6BY', 'UK', 55.7813536, -4.0360084, '+44 (0)1707 283500', 'hamilton@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead. Padel courts opening soon.', false),
  ('David Lloyd Hampton', 'directory', 'davidlloyd', 'dl:hampton', 'https://www.davidlloyd.co.uk/clubs/hampton/club-facilities/padel/', 'Staines Road, Hampton, Middlesex', 'Hampton', 'TW2 5JD', 'UK', 51.438079, -0.3681089, '+44 (0)1707 283500', 'hampton@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Harlow', 'directory', 'davidlloyd', 'dl:harlow', 'https://www.davidlloyd.co.uk/clubs/harlow/club-facilities/padel/', 'Newhall Way, Harlow Innovation Park', 'Harlow', 'CM17 9LX', 'UK', 51.774995, 0.130918, '01279 357255', 'Harlow@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Harrogate', 'directory', 'davidlloyd', 'dl:harrogate', 'https://www.davidlloyd.co.uk/clubs/harrogate/padel/', 'Oakdale Place, Harrogate, North Yorkshire', 'Harrogate', 'HG1 2LA', 'UK', 54.0010777, -1.5533496, '+44 (0)1707 283500', 'harrogate@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Hatfield', 'directory', 'davidlloyd', 'dl:hatfield', 'https://www.davidlloyd.co.uk/clubs/hatfield/club-facilities/padel/', 'The Hangar, Hatfield Business Park, Hatfield, Hertfordshire', 'Hatfield', 'AL10 9AX', 'UK', 51.7655922, -0.2438239, '+44 (0)1707 283500', 'hatfield@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Herne Bay', 'directory', 'davidlloyd', 'dl:herne-bay', 'https://www.davidlloyd.co.uk/clubs/herne-bay/club-facilities/padel/', 'The Boulevard, Altira Park', 'Herne Bay', 'CT6 6GZ', 'UK', 51.36243415193306, 1.148139230037393, '01227 949635', 'HerneBay@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Heston', 'directory', 'davidlloyd', 'dl:heston', 'https://www.davidlloyd.co.uk/clubs/heston/club-facilities/padel/', 'Southall Lane, Hounslow, Middlesex', 'Hounslow', 'TW5 9PE', 'UK', 51.4936493, -0.4019602, '+44 (0)1707 283500', 'heston@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Kettering', 'directory', 'davidlloyd', 'dl:kettering', 'https://www.davidlloyd.co.uk/clubs/kettering/club-facilities/padel/', 'Hanwood Park Avenue, Kettering, Northamptonshire', 'Kettering', 'NN15 6FQ', 'UK', 52.37803428945886, -0.6808141423278535, '01536 213420', 'sales.kettering@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Kings Hill', 'directory', 'davidlloyd', 'dl:kings-hill', 'https://www.davidlloyd.co.uk/clubs/kings-hill/club-facilities/padel/', '21 Kings Hill Avenue, West Malling, Kent', 'West Malling', 'ME19 4UA', 'UK', 51.2763534, 0.3925844, '+44 (0)1707 283500', 'kingshill@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead. Padel courts opening soon.', false),
  ('David Lloyd Leeds', 'directory', 'davidlloyd', 'dl:leeds', 'https://www.davidlloyd.co.uk/clubs/leeds/club-facilities/padel/', 'Tongue Lane, Moortown, Leeds, West Yorkshire', 'Leeds', 'LS6 4QW', 'UK', 53.843681, -1.550204, '+44 (0)1707 283500', 'leeds@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Leicester Narborough', 'directory', 'davidlloyd', 'dl:leicester-narborough', 'https://www.davidlloyd.co.uk/clubs/leicester-narborough/club-facilities/padel/', 'Carlton Park, Narborough, Leicester, Leicestershire', 'Leicester', 'LE19 0LF', 'UK', 52.5804295, -1.2073013, '+44 (0)1707 283500', 'narborough@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead. Padel courts opening soon.', false),
  ('David Lloyd Manchester North', 'directory', 'davidlloyd', 'dl:manchester-north', 'https://www.davidlloyd.co.uk/clubs/manchester-north/club-facilities/padel/', 'Heywood Old Road', 'Manchester', 'M24 4TH', 'UK', 53.5558148, -2.2366228, '+44 (0)1707 283500', 'manchesternorth@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Manchester Trafford City', 'directory', 'davidlloyd', 'dl:manchester-trafford-city', 'https://www.davidlloyd.co.uk/clubs/manchester-trafford-city/club-facilities/padel/', 'Barton Embankment, Trafford City', 'Manchester', 'M17 8RH', 'UK', 53.4702067, -2.3586689, '+44 (0)1707 283500', 'manchester@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Milton Keynes', 'directory', 'davidlloyd', 'dl:milton-keynes', 'https://www.davidlloyd.co.uk/clubs/milton-keynes/club-facilities/padel/', 'Livingstone Drive, Newlands, Milton Keynes, Buckinghamshire', 'Milton Keynes', 'MK15 0DL', 'UK', 52.0516563, -0.7314156, '+44 (0)1707 283500', 'miltonkeynes@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Newbury', 'directory', 'davidlloyd', 'dl:newbury', 'https://www.davidlloyd.co.uk/clubs/newbury/club-facilities/padel/', 'Monks Lane', 'Newbury', 'RG14 7RW', 'UK', 51.3826649, -1.335662, '+44 (0)1707 283500', 'newbury@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Northwood', 'directory', 'davidlloyd', 'dl:northwood', 'https://www.davidlloyd.co.uk/clubs/northwood/club-facilities/padel/', 'Ducks Hill Road, Northwood, London', 'Northwood', 'HA6 2DR', 'UK', 51.5980386, -0.4446848, '+44 (0)1707 283500', 'Northwood@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Norwich', 'directory', 'davidlloyd', 'dl:norwich', 'https://www.davidlloyd.co.uk/clubs/norwich/club-facilities/padel/', 'Drayton High Road, Drayton', 'Norwich', 'NR6 5DU', 'UK', 52.65195139999999, 1.2617284, '+44 (0)1707 283500', 'norwich@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead. Padel courts opening soon.', false),
  ('David Lloyd Notting Hill', 'directory', 'davidlloyd', 'dl:notting-hill', 'https://www.davidlloyd.co.uk/clubs/notting-hill/club-facilities/padel/', '1 Alfred Road', 'London', 'W2 5EU', 'UK', 51.5208435, -0.1940686, '+44 (0)1707 283500', 'nottinghill@harbourclub.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Nottingham West Bridgford', 'directory', 'davidlloyd', 'dl:nottingham-west-bridgford', 'https://www.davidlloyd.co.uk/clubs/nottingham-west-bridgford/club-facilities/padel/', 'Rugby Rd, West Bridgford, Nottingham, Nottinghamshire', 'Nottingham', 'NG2 7HX', 'UK', 52.9219103, -1.1397151, '+44 (0)1707 283500', 'westbridgford@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Poole', 'directory', 'davidlloyd', 'dl:poole', 'https://www.davidlloyd.co.uk/clubs/poole/club-facilities/padel/', '24 Cabot Lane', 'Poole', 'BH17 7BX', 'UK', 50.7443883, -1.9905006, '+44 (0)1707 283500', 'poole@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Purley', 'directory', 'davidlloyd', 'dl:purley', 'https://www.davidlloyd.co.uk/clubs/purley/club-facilities/padel/', 'Hannibal Way, Croydon, Surrey', 'Croydon', 'CR0 4RW', 'UK', 51.3577884, -0.124404, '+44 (0)1707 283500', 'purley@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Raynes Park', 'directory', 'davidlloyd', 'dl:raynes-park', 'https://www.davidlloyd.co.uk/clubs/raynes-park/club-facilities/padel/', 'Bushey Road, Raynes Park', 'London', 'SW20 8TE', 'UK', 51.4059884, -0.2225384, '0208 543 8021', 'raynespark@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Ringwood', 'directory', 'davidlloyd', 'dl:ringwood', 'https://www.davidlloyd.co.uk/clubs/ringwood/club-facilities/padel/', '242 Christchurch Road', 'Ringwood', 'BH24 3AS', 'UK', 50.8373503, -1.784347, '+44 (0)1707 283500', 'ringwood@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Royal Berkshire', 'directory', 'davidlloyd', 'dl:royal-berkshire', 'https://www.davidlloyd.co.uk/clubs/royal-berkshire/club-facilities/padel/', 'Nine Mile Ride', 'Bracknell', 'RG12 7PB', 'UK', 51.3873734, -0.7483836, '+44 (0)1707 283500', 'royalberkshire@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Rugby', 'directory', 'davidlloyd', 'dl:rugby', 'https://www.davidlloyd.co.uk/clubs/rugby/club-facilities/padel/', 'Crick Road', 'Rugby', 'CV23 0AB', 'UK', 52.3554199, -1.1826812, '01788222340', 'sales.rugby@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Shrewsbury', 'directory', 'davidlloyd', 'dl:shrewsbury', 'https://www.davidlloyd.co.uk/clubs/shrewsbury/club-facilities/padel/', 'Sundorne Road', 'Shrewsbury', 'SY1 4RG', 'UK', 52.727484, -2.710987, '+44 (0)1707 283500', 'shrewsbury@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Solihull Cranmore', 'directory', 'davidlloyd', 'dl:solihull-cranmore', 'https://www.davidlloyd.co.uk/clubs/solihull-cranmore/club-facilities/padel/', '247 Cranmore Boulevard, Shirley, Solihull, West Midlands', 'Solihull', 'B90 4ZL', 'UK', 52.39560729999999, -1.8094884, '+44 (0)1707 283500', 'solihullcranmore@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Southampton', 'directory', 'davidlloyd', 'dl:southampton', 'https://www.davidlloyd.co.uk/clubs/southampton/club-facilities/padel/', 'Off Browhill Way, Frogmore Lane, Southampton, Hampshire', 'Southampton', 'SO16 0XS', 'UK', 50.9344269, -1.4637602, '+44 (0)1707 283500', 'southampton@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Southampton West End', 'directory', 'davidlloyd', 'dl:southampton-west-end', 'https://www.davidlloyd.co.uk/clubs/southampton-west-end/club-facilities/padel/', 'Botley Road, West End', 'Southampton', 'SO30 3XA', 'UK', 50.9228506, -1.3031547, '+44 (0)1707 283500', 'southamptonwestend@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Southend', 'directory', 'davidlloyd', 'dl:southend', 'https://www.davidlloyd.co.uk/clubs/southend/club-facilities/padel/', 'Snakes Lane, Southend on Sea, Essex', 'Southend-on-Sea', 'SS2 6XT', 'UK', 51.5645325, 0.6678264, '+44 (0)1707 283500', 'southend@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd St Neots', 'directory', 'davidlloyd', 'dl:st-neots', 'https://www.davidlloyd.co.uk/clubs/st-neots/club-facilities/padel/', 'Nuffield Road', 'St Neots', 'PE19 0AA', 'UK', 52.223805, -0.24826, '+44 (0)1707 283500', null, 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Sudbury Hill', 'directory', 'davidlloyd', 'dl:sudbury-hill', 'https://www.davidlloyd.co.uk/clubs/sudbury-hill/club-facilities/padel/', 'Greenford Road, Greenford, Middlesex', 'Greenford', 'UB6 0HX', 'UK', 51.5567517, -0.3359298, '+44 (0)1707 283500', 'sudburyhill@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Swansea', 'directory', 'davidlloyd', 'dl:swansea', 'https://www.davidlloyd.co.uk/clubs/swansea/club-facilities/padel/', 'Llandarcy', 'Neath', 'SA10 6GZ', 'UK', 51.6476959, -3.8500589, '+44 (0)1707 283500', 'swansea@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Teesside', 'directory', 'davidlloyd', 'dl:teesside', 'https://www.davidlloyd.co.uk/clubs/teesside/club-facilities/padel/', 'Tees Barrage Way, Thornaby, Stockton-on-Tees, Cleveland', 'Stockton-on-Tees', 'TS17 6QA', 'UK', 54.5649823, -1.2867864, '+44 (0)1707 283500', 'teesside@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Warrington', 'directory', 'davidlloyd', 'dl:warrington', 'https://www.davidlloyd.co.uk/clubs/warrington/club-facilities/padel/', 'Cromwell Avenue South, Great Sankey, Warrington, Cheshire', 'Warrington', 'WA5 1HH', 'UK', 53.3870105, -2.6248428, '+44 (0)1707 283500', 'warrington@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Wickwoods', 'directory', 'davidlloyd', 'dl:wickwoods', 'https://www.davidlloyd.co.uk/clubs/wickwoods/club-facilities/padel/', 'Shaves Wood Lane, Albourne, Nr Hassocks, West Sussex', 'Hassocks', 'BN6 9DY', 'UK', 50.9193499, -0.2230678, '+44 (0)1707 283500', 'wickwoods@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd Worcester', 'directory', 'davidlloyd', 'dl:worcester', 'https://www.davidlloyd.co.uk/clubs/worcester/club-facilities/padel/', 'Warriors Way, Hindlip', 'Worcester', 'WR3 8ZE', 'UK', 52.2169853, -2.1617421, '+44 (0)1707 283500', 'worcester@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead. Padel courts opening soon.', false),
  ('David Lloyd Worthing', 'directory', 'davidlloyd', 'dl:worthing', 'https://www.davidlloyd.co.uk/clubs/worthing/club-facilities/padel/', 'Romany Road', 'Worthing', 'BN13 3DL', 'UK', 50.8266719, -0.4294783, '+44 (0)1707 283500', 'worthing@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false),
  ('David Lloyd York', 'directory', 'davidlloyd', 'dl:york', 'https://www.davidlloyd.co.uk/clubs/york/club-facilities/padel/', 'St John''s Playing Field, Hull Road', 'York', 'YO10 3LG', 'UK', 53.9538099, -1.0441468, '+44 (0)1707 283500', 'york@davidlloyd.co.uk', 'Padel at David Lloyd Clubs is for members. Book courts in the David Lloyd Clubs app up to 9 days ahead.', false)
on conflict (club_name) do update set
  source             = 'directory',
  external_provider  = 'davidlloyd',
  external_tenant_id = excluded.external_tenant_id,
  website            = excluded.website,
  latitude           = coalesce(clubs.latitude, excluded.latitude),
  longitude          = coalesce(clubs.longitude, excluded.longitude);
